version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
  - dependency-name: django
    versions:
    - "3.1"
